name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  image-folder:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  scaled:
    description: '0 if no images were found, 1 if all images were already scaled, 2 if some images were scaled'
runs:
  using: 'node12'
  main: 'dist/index.js'
