name: 'Scale Images'
description: 'This action will scale all images in the image-folder'
inputs:
  image-folder:
    description: 'The name of the folder that contains the images.'
    required: true
outputs:
  scaled:
    description: '0 if no images were found, 1 if all images were already scaled, 2 if some images were scaled'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'image'
  color: 'green'
