name: CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run scaling step
      id: scale
      uses: ./ # Uses an action in the root directory
      with:
       image-folder: 'test_images'

    - name: Check scaling output 0
      if: steps.scale.outputs.scaled == '0'
      run: echo "No images found"

    - name: Check scaling output 1
      if: steps.scale.outputs.scaled == '1'
      run: echo "All images were already scaled"

    - name: Check scaling output 2
      if: steps.scale.outputs.scaled == '2'
      run: echo "Some images were scaled"

    - name: Commit image files
      working-directory: test_images
      run: | 
        git config user.email "bot@turtlesec.no"
        git config user.name "Turtle Bot (GitHub Action)"
        if [[ "$( git status --porcelain)" != "" ]]; then
          git add -A
          git commit -m "Updated image files"
          git push
        fi
