name: CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run scaling step
      id: scale
      uses: ./ # Uses an action in the root directory
      with:
       image-folder: '/home/runner/work/scale-images-action/scale-images-action/test_images'
        
    - name: Commit image files
      working-directory: test_images
      run: | 
        pwd
        ls -ltr
        git config user.email "bot@turtlesec.no"
        git config user.name "Turtle Bot (GitHub Action)"
        if [[ "$( git status --porcelain *.png)" != "" ]]; then
          git add -A *.png
          git commit -m "Updated image files"
          git push
        fi
        
      # Use the output from the `hello` step
      #- name: Get the output time
      #  run: echo "The time was ${{ steps.hello.outputs.time }}"
